### ISSUE TITLE
Language innit

### ISSUE THREAD

**Issue by alfreaca** [HirobaSite/hiroba.xyz#22]
Seems cool but i don't understand japanese so like can you make an english login page, if there is one and I didn't see it, pretend like you just added it now so that i don't look dumb, thansk

**Comment by Piturnah** [comment]
Thank you very much for submitting a feature request, unfortunately, I am marking this issue as: `wontfix`

### Localisation and Hiroba
Hiroba was created as a generic forum for any kind of subject with specifically a Japanese userbase and content base in mind. While providing localisation is generally always a good idea for inclusivity, in this case it goes against the original reasoning for the project. There already exist many forums for English speaking users, and I believe providing localisation would take Hiroba out of its intended niche if supported so early.

For this reason, no localisation will be provided for Hiroba, for the time being. This doesn't rule out the possibility of returning to this idea in future once/if a predominantly Japanese content pool has been established. 

Thank you very much for raising this issue!
